/*
 * SujiSudokuSolverView.java
 */

package sujisudokusolver;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class SujiSudokuSolverView extends FrameView {

    public SujiSudokuSolverView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = SujiSudokuSolverApp.getApplication().getMainFrame();
            aboutBox = new SujiSudokuSolverAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        SujiSudokuSolverApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();
        jFormattedTextField13 = new javax.swing.JFormattedTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jFormattedTextField15 = new javax.swing.JFormattedTextField();
        jFormattedTextField16 = new javax.swing.JFormattedTextField();
        jFormattedTextField17 = new javax.swing.JFormattedTextField();
        jFormattedTextField18 = new javax.swing.JFormattedTextField();
        jFormattedTextField19 = new javax.swing.JFormattedTextField();
        jFormattedTextField20 = new javax.swing.JFormattedTextField();
        jFormattedTextField21 = new javax.swing.JFormattedTextField();
        jFormattedTextField22 = new javax.swing.JFormattedTextField();
        jFormattedTextField23 = new javax.swing.JFormattedTextField();
        jFormattedTextField24 = new javax.swing.JFormattedTextField();
        jFormattedTextField25 = new javax.swing.JFormattedTextField();
        jFormattedTextField26 = new javax.swing.JFormattedTextField();
        jFormattedTextField27 = new javax.swing.JFormattedTextField();
        jFormattedTextField28 = new javax.swing.JFormattedTextField();
        jFormattedTextField29 = new javax.swing.JFormattedTextField();
        jFormattedTextField30 = new javax.swing.JFormattedTextField();
        jFormattedTextField31 = new javax.swing.JFormattedTextField();
        jFormattedTextField32 = new javax.swing.JFormattedTextField();
        jFormattedTextField33 = new javax.swing.JFormattedTextField();
        jFormattedTextField34 = new javax.swing.JFormattedTextField();
        jFormattedTextField35 = new javax.swing.JFormattedTextField();
        jFormattedTextField36 = new javax.swing.JFormattedTextField();
        jFormattedTextField37 = new javax.swing.JFormattedTextField();
        jFormattedTextField38 = new javax.swing.JFormattedTextField();
        jFormattedTextField39 = new javax.swing.JFormattedTextField();
        jFormattedTextField40 = new javax.swing.JFormattedTextField();
        jFormattedTextField41 = new javax.swing.JFormattedTextField();
        jFormattedTextField42 = new javax.swing.JFormattedTextField();
        jFormattedTextField43 = new javax.swing.JFormattedTextField();
        jFormattedTextField44 = new javax.swing.JFormattedTextField();
        jFormattedTextField45 = new javax.swing.JFormattedTextField();
        jFormattedTextField46 = new javax.swing.JFormattedTextField();
        jFormattedTextField47 = new javax.swing.JFormattedTextField();
        jFormattedTextField48 = new javax.swing.JFormattedTextField();
        jFormattedTextField49 = new javax.swing.JFormattedTextField();
        jFormattedTextField50 = new javax.swing.JFormattedTextField();
        jFormattedTextField51 = new javax.swing.JFormattedTextField();
        jFormattedTextField52 = new javax.swing.JFormattedTextField();
        jFormattedTextField53 = new javax.swing.JFormattedTextField();
        jFormattedTextField54 = new javax.swing.JFormattedTextField();
        jFormattedTextField55 = new javax.swing.JFormattedTextField();
        jFormattedTextField56 = new javax.swing.JFormattedTextField();
        jFormattedTextField57 = new javax.swing.JFormattedTextField();
        jFormattedTextField58 = new javax.swing.JFormattedTextField();
        jFormattedTextField59 = new javax.swing.JFormattedTextField();
        jFormattedTextField60 = new javax.swing.JFormattedTextField();
        jFormattedTextField61 = new javax.swing.JFormattedTextField();
        jFormattedTextField62 = new javax.swing.JFormattedTextField();
        jFormattedTextField63 = new javax.swing.JFormattedTextField();
        jFormattedTextField64 = new javax.swing.JFormattedTextField();
        jFormattedTextField65 = new javax.swing.JFormattedTextField();
        jFormattedTextField66 = new javax.swing.JFormattedTextField();
        jFormattedTextField67 = new javax.swing.JFormattedTextField();
        jFormattedTextField68 = new javax.swing.JFormattedTextField();
        jFormattedTextField69 = new javax.swing.JFormattedTextField();
        jFormattedTextField70 = new javax.swing.JFormattedTextField();
        jFormattedTextField71 = new javax.swing.JFormattedTextField();
        jFormattedTextField72 = new javax.swing.JFormattedTextField();
        jFormattedTextField73 = new javax.swing.JFormattedTextField();
        jFormattedTextField74 = new javax.swing.JFormattedTextField();
        jFormattedTextField75 = new javax.swing.JFormattedTextField();
        jFormattedTextField76 = new javax.swing.JFormattedTextField();
        jFormattedTextField77 = new javax.swing.JFormattedTextField();
        jFormattedTextField78 = new javax.swing.JFormattedTextField();
        jFormattedTextField79 = new javax.swing.JFormattedTextField();
        jFormattedTextField80 = new javax.swing.JFormattedTextField();
        jFormattedTextField81 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(sujisudokusolver.SujiSudokuSolverApp.class).getContext().getResourceMap(SujiSudokuSolverView.class);
        jFormattedTextField1.setText(resourceMap.getString("jFormattedTextField1.text")); // NOI18N
        jFormattedTextField1.setFont(resourceMap.getFont("jFormattedTextField1.font")); // NOI18N
        jFormattedTextField1.setName("jFormattedTextField1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setFont(resourceMap.getFont("jFormattedTextField2.font")); // NOI18N
        jFormattedTextField2.setName("jFormattedTextField2"); // NOI18N

        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.setFont(resourceMap.getFont("jFormattedTextField3.font")); // NOI18N
        jFormattedTextField3.setName("jFormattedTextField3"); // NOI18N

        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField4.setFont(resourceMap.getFont("jFormattedTextField4.font")); // NOI18N
        jFormattedTextField4.setName("jFormattedTextField4"); // NOI18N

        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField5.setFont(resourceMap.getFont("jFormattedTextField5.font")); // NOI18N
        jFormattedTextField5.setName("jFormattedTextField5"); // NOI18N

        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.setFont(resourceMap.getFont("jFormattedTextField6.font")); // NOI18N
        jFormattedTextField6.setName("jFormattedTextField6"); // NOI18N

        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField7.setFont(resourceMap.getFont("jFormattedTextField7.font")); // NOI18N
        jFormattedTextField7.setName("jFormattedTextField7"); // NOI18N

        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField8.setFont(resourceMap.getFont("jFormattedTextField8.font")); // NOI18N
        jFormattedTextField8.setName("jFormattedTextField8"); // NOI18N

        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField9.setFont(resourceMap.getFont("jFormattedTextField9.font")); // NOI18N
        jFormattedTextField9.setName("jFormattedTextField9"); // NOI18N

        jFormattedTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField10.setFont(resourceMap.getFont("jFormattedTextField10.font")); // NOI18N
        jFormattedTextField10.setName("jFormattedTextField10"); // NOI18N

        jFormattedTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField11.setFont(resourceMap.getFont("jFormattedTextField11.font")); // NOI18N
        jFormattedTextField11.setName("jFormattedTextField11"); // NOI18N

        jFormattedTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField12.setFont(resourceMap.getFont("jFormattedTextField12.font")); // NOI18N
        jFormattedTextField12.setName("jFormattedTextField12"); // NOI18N

        jFormattedTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField13.setFont(resourceMap.getFont("jFormattedTextField13.font")); // NOI18N
        jFormattedTextField13.setName("jFormattedTextField13"); // NOI18N

        jFormattedTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField14.setFont(resourceMap.getFont("jFormattedTextField14.font")); // NOI18N
        jFormattedTextField14.setName("jFormattedTextField14"); // NOI18N

        jFormattedTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField15.setFont(resourceMap.getFont("jFormattedTextField15.font")); // NOI18N
        jFormattedTextField15.setName("jFormattedTextField15"); // NOI18N

        jFormattedTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField16.setFont(resourceMap.getFont("jFormattedTextField16.font")); // NOI18N
        jFormattedTextField16.setName("jFormattedTextField16"); // NOI18N

        jFormattedTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField17.setFont(resourceMap.getFont("jFormattedTextField17.font")); // NOI18N
        jFormattedTextField17.setName("jFormattedTextField17"); // NOI18N

        jFormattedTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField18.setFont(resourceMap.getFont("jFormattedTextField18.font")); // NOI18N
        jFormattedTextField18.setName("jFormattedTextField18"); // NOI18N

        jFormattedTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField19.setFont(resourceMap.getFont("jFormattedTextField19.font")); // NOI18N
        jFormattedTextField19.setName("jFormattedTextField19"); // NOI18N

        jFormattedTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField20.setFont(resourceMap.getFont("jFormattedTextField20.font")); // NOI18N
        jFormattedTextField20.setName("jFormattedTextField20"); // NOI18N

        jFormattedTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField21.setFont(resourceMap.getFont("jFormattedTextField21.font")); // NOI18N
        jFormattedTextField21.setName("jFormattedTextField21"); // NOI18N

        jFormattedTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField22.setFont(resourceMap.getFont("jFormattedTextField22.font")); // NOI18N
        jFormattedTextField22.setName("jFormattedTextField22"); // NOI18N

        jFormattedTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField23.setFont(resourceMap.getFont("jFormattedTextField23.font")); // NOI18N
        jFormattedTextField23.setName("jFormattedTextField23"); // NOI18N

        jFormattedTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField24.setFont(resourceMap.getFont("jFormattedTextField24.font")); // NOI18N
        jFormattedTextField24.setName("jFormattedTextField24"); // NOI18N

        jFormattedTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField25.setFont(resourceMap.getFont("jFormattedTextField25.font")); // NOI18N
        jFormattedTextField25.setName("jFormattedTextField25"); // NOI18N

        jFormattedTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField26.setFont(resourceMap.getFont("jFormattedTextField26.font")); // NOI18N
        jFormattedTextField26.setName("jFormattedTextField26"); // NOI18N

        jFormattedTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField27.setFont(resourceMap.getFont("jFormattedTextField27.font")); // NOI18N
        jFormattedTextField27.setName("jFormattedTextField27"); // NOI18N

        jFormattedTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField28.setFont(resourceMap.getFont("jFormattedTextField28.font")); // NOI18N
        jFormattedTextField28.setName("jFormattedTextField28"); // NOI18N

        jFormattedTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField29.setFont(resourceMap.getFont("jFormattedTextField29.font")); // NOI18N
        jFormattedTextField29.setName("jFormattedTextField29"); // NOI18N

        jFormattedTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField30.setFont(resourceMap.getFont("jFormattedTextField30.font")); // NOI18N
        jFormattedTextField30.setName("jFormattedTextField30"); // NOI18N

        jFormattedTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField31.setFont(resourceMap.getFont("jFormattedTextField31.font")); // NOI18N
        jFormattedTextField31.setName("jFormattedTextField31"); // NOI18N

        jFormattedTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField32.setFont(resourceMap.getFont("jFormattedTextField32.font")); // NOI18N
        jFormattedTextField32.setName("jFormattedTextField32"); // NOI18N

        jFormattedTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField33.setFont(resourceMap.getFont("jFormattedTextField33.font")); // NOI18N
        jFormattedTextField33.setName("jFormattedTextField33"); // NOI18N

        jFormattedTextField34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField34.setFont(resourceMap.getFont("jFormattedTextField34.font")); // NOI18N
        jFormattedTextField34.setName("jFormattedTextField34"); // NOI18N

        jFormattedTextField35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField35.setFont(resourceMap.getFont("jFormattedTextField35.font")); // NOI18N
        jFormattedTextField35.setName("jFormattedTextField35"); // NOI18N

        jFormattedTextField36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField36.setFont(resourceMap.getFont("jFormattedTextField36.font")); // NOI18N
        jFormattedTextField36.setName("jFormattedTextField36"); // NOI18N

        jFormattedTextField37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField37.setFont(resourceMap.getFont("jFormattedTextField37.font")); // NOI18N
        jFormattedTextField37.setName("jFormattedTextField37"); // NOI18N

        jFormattedTextField38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField38.setFont(resourceMap.getFont("jFormattedTextField38.font")); // NOI18N
        jFormattedTextField38.setName("jFormattedTextField38"); // NOI18N

        jFormattedTextField39.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField39.setFont(resourceMap.getFont("jFormattedTextField39.font")); // NOI18N
        jFormattedTextField39.setName("jFormattedTextField39"); // NOI18N

        jFormattedTextField40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField40.setFont(resourceMap.getFont("jFormattedTextField40.font")); // NOI18N
        jFormattedTextField40.setName("jFormattedTextField40"); // NOI18N

        jFormattedTextField41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField41.setFont(resourceMap.getFont("jFormattedTextField41.font")); // NOI18N
        jFormattedTextField41.setName("jFormattedTextField41"); // NOI18N

        jFormattedTextField42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField42.setFont(resourceMap.getFont("jFormattedTextField42.font")); // NOI18N
        jFormattedTextField42.setName("jFormattedTextField42"); // NOI18N

        jFormattedTextField43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField43.setFont(resourceMap.getFont("jFormattedTextField43.font")); // NOI18N
        jFormattedTextField43.setName("jFormattedTextField43"); // NOI18N

        jFormattedTextField44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField44.setFont(resourceMap.getFont("jFormattedTextField44.font")); // NOI18N
        jFormattedTextField44.setName("jFormattedTextField44"); // NOI18N

        jFormattedTextField45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField45.setFont(resourceMap.getFont("jFormattedTextField45.font")); // NOI18N
        jFormattedTextField45.setName("jFormattedTextField45"); // NOI18N

        jFormattedTextField46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField46.setFont(resourceMap.getFont("jFormattedTextField46.font")); // NOI18N
        jFormattedTextField46.setName("jFormattedTextField46"); // NOI18N

        jFormattedTextField47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField47.setFont(resourceMap.getFont("jFormattedTextField47.font")); // NOI18N
        jFormattedTextField47.setName("jFormattedTextField47"); // NOI18N

        jFormattedTextField48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField48.setFont(resourceMap.getFont("jFormattedTextField48.font")); // NOI18N
        jFormattedTextField48.setName("jFormattedTextField48"); // NOI18N

        jFormattedTextField49.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField49.setFont(resourceMap.getFont("jFormattedTextField49.font")); // NOI18N
        jFormattedTextField49.setName("jFormattedTextField49"); // NOI18N

        jFormattedTextField50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField50.setFont(resourceMap.getFont("jFormattedTextField50.font")); // NOI18N
        jFormattedTextField50.setName("jFormattedTextField50"); // NOI18N

        jFormattedTextField51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField51.setText(resourceMap.getString("jFormattedTextField51.text")); // NOI18N
        jFormattedTextField51.setFont(resourceMap.getFont("jFormattedTextField51.font")); // NOI18N
        jFormattedTextField51.setName("jFormattedTextField51"); // NOI18N

        jFormattedTextField52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField52.setFont(resourceMap.getFont("jFormattedTextField52.font")); // NOI18N
        jFormattedTextField52.setName("jFormattedTextField52"); // NOI18N

        jFormattedTextField53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField53.setFont(resourceMap.getFont("jFormattedTextField53.font")); // NOI18N
        jFormattedTextField53.setName("jFormattedTextField53"); // NOI18N

        jFormattedTextField54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField54.setFont(resourceMap.getFont("jFormattedTextField54.font")); // NOI18N
        jFormattedTextField54.setName("jFormattedTextField54"); // NOI18N

        jFormattedTextField55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField55.setFont(resourceMap.getFont("jFormattedTextField55.font")); // NOI18N
        jFormattedTextField55.setName("jFormattedTextField55"); // NOI18N

        jFormattedTextField56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField56.setFont(resourceMap.getFont("jFormattedTextField56.font")); // NOI18N
        jFormattedTextField56.setName("jFormattedTextField56"); // NOI18N

        jFormattedTextField57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField57.setFont(resourceMap.getFont("jFormattedTextField57.font")); // NOI18N
        jFormattedTextField57.setName("jFormattedTextField57"); // NOI18N

        jFormattedTextField58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField58.setFont(resourceMap.getFont("jFormattedTextField58.font")); // NOI18N
        jFormattedTextField58.setName("jFormattedTextField58"); // NOI18N

        jFormattedTextField59.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField59.setFont(resourceMap.getFont("jFormattedTextField59.font")); // NOI18N
        jFormattedTextField59.setName("jFormattedTextField59"); // NOI18N

        jFormattedTextField60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField60.setFont(resourceMap.getFont("jFormattedTextField60.font")); // NOI18N
        jFormattedTextField60.setName("jFormattedTextField60"); // NOI18N

        jFormattedTextField61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField61.setFont(resourceMap.getFont("jFormattedTextField61.font")); // NOI18N
        jFormattedTextField61.setName("jFormattedTextField61"); // NOI18N

        jFormattedTextField62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField62.setFont(resourceMap.getFont("jFormattedTextField62.font")); // NOI18N
        jFormattedTextField62.setName("jFormattedTextField62"); // NOI18N

        jFormattedTextField63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField63.setFont(resourceMap.getFont("jFormattedTextField63.font")); // NOI18N
        jFormattedTextField63.setName("jFormattedTextField63"); // NOI18N

        jFormattedTextField64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField64.setFont(resourceMap.getFont("jFormattedTextField64.font")); // NOI18N
        jFormattedTextField64.setName("jFormattedTextField64"); // NOI18N

        jFormattedTextField65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField65.setFont(resourceMap.getFont("jFormattedTextField65.font")); // NOI18N
        jFormattedTextField65.setName("jFormattedTextField65"); // NOI18N

        jFormattedTextField66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField66.setName("jFormattedTextField66"); // NOI18N

        jFormattedTextField67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField67.setFont(resourceMap.getFont("jFormattedTextField67.font")); // NOI18N
        jFormattedTextField67.setName("jFormattedTextField67"); // NOI18N

        jFormattedTextField68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField68.setFont(resourceMap.getFont("jFormattedTextField68.font")); // NOI18N
        jFormattedTextField68.setName("jFormattedTextField68"); // NOI18N

        jFormattedTextField69.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField69.setFont(resourceMap.getFont("jFormattedTextField69.font")); // NOI18N
        jFormattedTextField69.setName("jFormattedTextField69"); // NOI18N

        jFormattedTextField70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField70.setFont(resourceMap.getFont("jFormattedTextField70.font")); // NOI18N
        jFormattedTextField70.setName("jFormattedTextField70"); // NOI18N

        jFormattedTextField71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField71.setFont(resourceMap.getFont("jFormattedTextField71.font")); // NOI18N
        jFormattedTextField71.setName("jFormattedTextField71"); // NOI18N

        jFormattedTextField72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField72.setFont(resourceMap.getFont("jFormattedTextField72.font")); // NOI18N
        jFormattedTextField72.setName("jFormattedTextField72"); // NOI18N

        jFormattedTextField73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField73.setFont(resourceMap.getFont("jFormattedTextField73.font")); // NOI18N
        jFormattedTextField73.setName("jFormattedTextField73"); // NOI18N

        jFormattedTextField74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField74.setFont(resourceMap.getFont("jFormattedTextField74.font")); // NOI18N
        jFormattedTextField74.setName("jFormattedTextField74"); // NOI18N

        jFormattedTextField75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField75.setText(resourceMap.getString("jFormattedTextField75.text")); // NOI18N
        jFormattedTextField75.setFont(resourceMap.getFont("jFormattedTextField75.font")); // NOI18N
        jFormattedTextField75.setName("jFormattedTextField75"); // NOI18N

        jFormattedTextField76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField76.setName("jFormattedTextField76"); // NOI18N

        jFormattedTextField77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField77.setFont(resourceMap.getFont("jFormattedTextField77.font")); // NOI18N
        jFormattedTextField77.setName("jFormattedTextField77"); // NOI18N

        jFormattedTextField78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField78.setFont(resourceMap.getFont("jFormattedTextField78.font")); // NOI18N
        jFormattedTextField78.setName("jFormattedTextField78"); // NOI18N

        jFormattedTextField79.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField79.setFont(resourceMap.getFont("jFormattedTextField79.font")); // NOI18N
        jFormattedTextField79.setName("jFormattedTextField79"); // NOI18N

        jFormattedTextField80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField80.setFont(resourceMap.getFont("jFormattedTextField80.font")); // NOI18N
        jFormattedTextField80.setName("jFormattedTextField80"); // NOI18N

        jFormattedTextField81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField81.setFont(resourceMap.getFont("jFormattedTextField81.font")); // NOI18N
        jFormattedTextField81.setName("jFormattedTextField81"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setBackground(resourceMap.getColor("jTextArea1.background")); // NOI18N
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(resourceMap.getColor("jTextArea1.foreground")); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText(resourceMap.getString("jTextArea1.text")); // NOI18N
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jFormattedTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField39, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField49, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField59, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField69, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFormattedTextField79, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextField81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(sujisudokusolver.SujiSudokuSolverApp.class).getContext().getActionMap(SujiSudokuSolverView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 470, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField15;
    private javax.swing.JFormattedTextField jFormattedTextField16;
    private javax.swing.JFormattedTextField jFormattedTextField17;
    private javax.swing.JFormattedTextField jFormattedTextField18;
    private javax.swing.JFormattedTextField jFormattedTextField19;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField20;
    private javax.swing.JFormattedTextField jFormattedTextField21;
    private javax.swing.JFormattedTextField jFormattedTextField22;
    private javax.swing.JFormattedTextField jFormattedTextField23;
    private javax.swing.JFormattedTextField jFormattedTextField24;
    private javax.swing.JFormattedTextField jFormattedTextField25;
    private javax.swing.JFormattedTextField jFormattedTextField26;
    private javax.swing.JFormattedTextField jFormattedTextField27;
    private javax.swing.JFormattedTextField jFormattedTextField28;
    private javax.swing.JFormattedTextField jFormattedTextField29;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField30;
    private javax.swing.JFormattedTextField jFormattedTextField31;
    private javax.swing.JFormattedTextField jFormattedTextField32;
    private javax.swing.JFormattedTextField jFormattedTextField33;
    private javax.swing.JFormattedTextField jFormattedTextField34;
    private javax.swing.JFormattedTextField jFormattedTextField35;
    private javax.swing.JFormattedTextField jFormattedTextField36;
    private javax.swing.JFormattedTextField jFormattedTextField37;
    private javax.swing.JFormattedTextField jFormattedTextField38;
    private javax.swing.JFormattedTextField jFormattedTextField39;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField40;
    private javax.swing.JFormattedTextField jFormattedTextField41;
    private javax.swing.JFormattedTextField jFormattedTextField42;
    private javax.swing.JFormattedTextField jFormattedTextField43;
    private javax.swing.JFormattedTextField jFormattedTextField44;
    private javax.swing.JFormattedTextField jFormattedTextField45;
    private javax.swing.JFormattedTextField jFormattedTextField46;
    private javax.swing.JFormattedTextField jFormattedTextField47;
    private javax.swing.JFormattedTextField jFormattedTextField48;
    private javax.swing.JFormattedTextField jFormattedTextField49;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField50;
    private javax.swing.JFormattedTextField jFormattedTextField51;
    private javax.swing.JFormattedTextField jFormattedTextField52;
    private javax.swing.JFormattedTextField jFormattedTextField53;
    private javax.swing.JFormattedTextField jFormattedTextField54;
    private javax.swing.JFormattedTextField jFormattedTextField55;
    private javax.swing.JFormattedTextField jFormattedTextField56;
    private javax.swing.JFormattedTextField jFormattedTextField57;
    private javax.swing.JFormattedTextField jFormattedTextField58;
    private javax.swing.JFormattedTextField jFormattedTextField59;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField60;
    private javax.swing.JFormattedTextField jFormattedTextField61;
    private javax.swing.JFormattedTextField jFormattedTextField62;
    private javax.swing.JFormattedTextField jFormattedTextField63;
    private javax.swing.JFormattedTextField jFormattedTextField64;
    private javax.swing.JFormattedTextField jFormattedTextField65;
    private javax.swing.JFormattedTextField jFormattedTextField66;
    private javax.swing.JFormattedTextField jFormattedTextField67;
    private javax.swing.JFormattedTextField jFormattedTextField68;
    private javax.swing.JFormattedTextField jFormattedTextField69;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField70;
    private javax.swing.JFormattedTextField jFormattedTextField71;
    private javax.swing.JFormattedTextField jFormattedTextField72;
    private javax.swing.JFormattedTextField jFormattedTextField73;
    private javax.swing.JFormattedTextField jFormattedTextField74;
    private javax.swing.JFormattedTextField jFormattedTextField75;
    private javax.swing.JFormattedTextField jFormattedTextField76;
    private javax.swing.JFormattedTextField jFormattedTextField77;
    private javax.swing.JFormattedTextField jFormattedTextField78;
    private javax.swing.JFormattedTextField jFormattedTextField79;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField80;
    private javax.swing.JFormattedTextField jFormattedTextField81;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
